import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import slugify from "slugify";

const prisma = new PrismaClient();

const categories = [
  { name: "Outerwear", imageUrl: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800" },
  { name: "Knitwear", imageUrl: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=800" },
  { name: "Tailoring", imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800" },
  { name: "Basics", imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800" },
  { name: "Denim", imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800" },
];

const products = [
  {
    name: "Wool Overcoat",
    category: "Outerwear",
    description: "A structured double-breasted overcoat cut from heavyweight Italian wool.",
    story: "Cut from a mill in Biella, this coat is built for a decade of winters, not one season.",
    price: 4299,
    compareAtPrice: 4999,
    images: ["https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Charcoal", "Camel"],
    material: "90% wool, 10% cashmere",
    stock: 24,
    sku: "VLR-OC-001",
    featured: true,
  },
  {
    name: "Alpaca Crewneck",
    category: "Knitwear",
    description: "Featherweight alpaca crewneck with a relaxed drop shoulder.",
    price: 2399,
    images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=900"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Ivory", "Forest", "Stone"],
    material: "100% baby alpaca",
    stock: 40,
    sku: "VLR-KN-002",
    featured: true,
    isNewArrival: true,
  },
  {
    name: "Tailored Wool Trouser",
    category: "Tailoring",
    description: "A clean-line trouser with a high rise and tapered leg, finished with a satin waistband.",
    price: 2999,
    images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=900"],
    sizes: ["24", "26", "28", "30", "32"],
    colors: ["Black", "Graphite"],
    material: "100% virgin wool",
    stock: 30,
    sku: "VLR-TL-003",
    featured: true,
  },
  {
    name: "Structured Blazer",
    category: "Tailoring",
    description: "Single-breasted blazer with a soft shoulder and half-canvas construction.",
    price: 3899,
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy"],
    material: "Wool blend",
    stock: 18,
    sku: "VLR-TL-004",
    featured: true,
  },
  {
    name: "Organic Cotton Tee",
    category: "Basics",
    description: "Heavyweight 220gsm organic cotton tee with a boxy, considered fit.",
    price: 999,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Clay"],
    material: "100% organic cotton",
    stock: 120,
    sku: "VLR-BS-005",
    isNewArrival: true,
    featured: true,
  },
  {
    name: "Straight Leg Jean",
    category: "Denim",
    description: "Rigid selvedge denim in a straight cut that softens with wear.",
    price: 2799,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=900"],
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Indigo", "Black"],
    material: "100% cotton selvedge denim",
    stock: 55,
    sku: "VLR-DN-006",
    featured: true,
  },
  {
    name: "Merino Turtleneck",
    category: "Knitwear",
    description: "Fine-gauge merino turtleneck, cut close without clinging.",
    price: 2299,
    images: ["https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=900"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Ivory", "Burgundy"],
    material: "100% merino wool",
    stock: 33,
    sku: "VLR-KN-007",
    featured: true,
  },
  {
    name: "Shearling Aviator Jacket",
    category: "Outerwear",
    description: "Suede aviator jacket lined in genuine shearling for serious cold.",
    price: 4799,
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cognac"],
    material: "Suede, shearling lining",
    stock: 9,
    sku: "VLR-OC-008",
    featured: true,
  },

  // --- Outerwear (+6) ---
  {
    name: "Quilted Field Jacket",
    category: "Outerwear",
    description: "A lightweight quilted jacket with a stand collar, built for cold mornings.",
    price: 3799,
    images: ["https://images.unsplash.com/photo-1647864019646-e446b0135941?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive", "Black"],
    material: "Cotton shell, recycled fill",
    stock: 28,
    sku: "VLR-OC-009",
  },
  {
    name: "Waxed Cotton Trench",
    category: "Outerwear",
    description: "A weatherproof trench in waxed cotton with a storm flap and belt.",
    price: 4599,
    images: ["https://images.unsplash.com/photo-1602677416425-c84311bd217c?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Olive", "Stone"],
    material: "Waxed cotton",
    stock: 16,
    sku: "VLR-OC-010",
  },
  {
    name: "Padded Puffer Coat",
    category: "Outerwear",
    description: "A long puffer with a matte shell and channel quilting for real warmth.",
    price: 3999,
    images: ["https://images.unsplash.com/photo-1586972409498-2c938103a7ed?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Camel"],
    material: "Recycled nylon shell, down-alternative fill",
    stock: 22,
    sku: "VLR-OC-011",
  },
  {
    name: "Wool-Blend Peacoat",
    category: "Outerwear",
    description: "A double-breasted peacoat with horn-style buttons and a full lining.",
    price: 4199,
    images: ["https://images.unsplash.com/photo-1761882255997-28cb59ef3b6c?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy", "Charcoal"],
    material: "80% wool, 20% polyester",
    stock: 19,
    sku: "VLR-OC-012",
  },
  {
    name: "Corduroy Chore Jacket",
    category: "Outerwear",
    description: "A boxy chore jacket in wide-wale corduroy with patch pockets.",
    price: 3499,
    images: ["https://images.unsplash.com/photo-1616702451225-6671e7e831f8?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Rust", "Olive"],
    material: "100% cotton corduroy",
    stock: 31,
    sku: "VLR-OC-013",
    isNewArrival: true,
  },
  {
    name: "Leather Biker Jacket",
    category: "Outerwear",
    description: "An asymmetric zip biker jacket in supple lamb leather.",
    price: 4999,
    images: ["https://images.unsplash.com/photo-1613498382159-0972b7b4c9f1?w=900"],
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    material: "100% lamb leather",
    stock: 8,
    sku: "VLR-OC-014",
  },

  // --- Knitwear (+6) ---
  {
    name: "Cable Knit Cardigan",
    category: "Knitwear",
    description: "A chunky cable-knit cardigan with horn buttons and patch pockets.",
    price: 3099,
    images: ["https://images.unsplash.com/photo-1765114470103-b68286cf9c6d?w=900"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Oatmeal", "Charcoal"],
    material: "100% lambswool",
    stock: 26,
    sku: "VLR-KN-015",
  },
  {
    name: "Cashmere V-Neck",
    category: "Knitwear",
    description: "A featherlight cashmere V-neck that layers cleanly under tailoring.",
    price: 3799,
    images: ["https://images.unsplash.com/photo-1626554660626-2d11b2f9e780?w=900"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Camel", "Navy", "Black"],
    material: "100% cashmere",
    stock: 20,
    sku: "VLR-KN-016",
    isNewArrival: true,
  },
  {
    name: "Shetland Wool Sweater",
    category: "Knitwear",
    description: "A traditional Shetland crewneck with a slightly textured hand.",
    price: 2699,
    images: ["https://images.unsplash.com/photo-1581497396202-5645e76a3a8e?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Heather Grey", "Forest"],
    material: "100% Shetland wool",
    stock: 34,
    sku: "VLR-KN-017",
  },
  {
    name: "Ribbed Roll-Neck",
    category: "Knitwear",
    description: "A close-fitting ribbed roll-neck in a fine merino gauge.",
    price: 2499,
    images: ["https://images.unsplash.com/photo-1605980776566-0486c3ac7617?w=900"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Ivory"],
    material: "100% merino wool",
    stock: 29,
    sku: "VLR-KN-018",
  },
  {
    name: "Lambswool Half-Zip",
    category: "Knitwear",
    description: "A half-zip pullover in soft lambswool, cut for easy layering.",
    price: 2899,
    images: ["https://images.unsplash.com/photo-1522751707891-45b4e281010d?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Stone", "Navy"],
    material: "100% lambswool",
    stock: 24,
    sku: "VLR-KN-019",
  },
  {
    name: "Chunky Knit Poncho",
    category: "Knitwear",
    description: "An oversized poncho in a chunky open-stitch knit with fringe trim.",
    price: 2799,
    images: ["https://images.unsplash.com/photo-1519635217-af1ee5afc6ec?w=900"],
    sizes: ["One Size"],
    colors: ["Ivory", "Camel"],
    material: "Wool-acrylic blend",
    stock: 15,
    sku: "VLR-KN-020",
  },

  // --- Tailoring (+6) ---
  {
    name: "Pleated Wide-Leg Trouser",
    category: "Tailoring",
    description: "A double-pleated trouser with a relaxed wide leg and a soft drape.",
    price: 3099,
    images: ["https://images.unsplash.com/photo-1578758837674-93ed0ab5fbab?w=900"],
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Black", "Taupe"],
    material: "Wool blend",
    stock: 27,
    sku: "VLR-TL-021",
  },
  {
    name: "Double-Breasted Blazer",
    category: "Tailoring",
    description: "A six-button double-breasted blazer with peak lapels.",
    price: 4399,
    images: ["https://images.unsplash.com/photo-1549998966-8e0e3e5e83ad?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Charcoal"],
    material: "Wool blend",
    stock: 14,
    sku: "VLR-TL-022",
  },
  {
    name: "Linen Suit Jacket",
    category: "Tailoring",
    description: "An unstructured suit jacket in breathable linen for warm-weather tailoring.",
    price: 4099,
    images: ["https://images.unsplash.com/photo-1611000784352-a67afb821041?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Stone", "Navy"],
    material: "100% linen",
    stock: 18,
    sku: "VLR-TL-023",
    isNewArrival: true,
  },
  {
    name: "Tapered Dress Trouser",
    category: "Tailoring",
    description: "A slim, tapered trouser finished with a clean waistband and no break.",
    price: 2799,
    images: ["https://images.unsplash.com/photo-1736939615657-590b2dce72cc?w=900"],
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Black", "Navy", "Graphite"],
    material: "Wool blend",
    stock: 32,
    sku: "VLR-TL-024",
  },
  {
    name: "Wool Waistcoat",
    category: "Tailoring",
    description: "A five-button waistcoat cut to layer under a blazer or worn alone.",
    price: 2599,
    images: ["https://images.unsplash.com/photo-1592343516109-362f7bd871aa?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Charcoal", "Navy"],
    material: "Wool blend",
    stock: 21,
    sku: "VLR-TL-025",
  },
  {
    name: "Herringbone Overshirt",
    category: "Tailoring",
    description: "A structured overshirt in herringbone wool, worn open or buttoned.",
    price: 3299,
    images: ["https://images.unsplash.com/photo-1602295456965-49e52ca85874?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Brown"],
    material: "Wool blend",
    stock: 23,
    sku: "VLR-TL-026",
  },

  // --- Basics (+7) ---
  {
    name: "Crew Neck Sweatshirt",
    category: "Basics",
    description: "A heavyweight loopback crew sweatshirt with a boxy, considered fit.",
    price: 1799,
    images: ["https://images.unsplash.com/photo-1563074409-5c5d31af4e94?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Grey", "Black", "Ivory"],
    material: "100% cotton loopback",
    stock: 60,
    sku: "VLR-BS-027",
  },
  {
    name: "Long-Sleeve Henley",
    category: "Basics",
    description: "A three-button henley in a mid-weight jersey with a clean placket.",
    price: 1299,
    images: ["https://images.unsplash.com/photo-1505165881430-81f6a7798388?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Navy", "Clay"],
    material: "100% cotton jersey",
    stock: 55,
    sku: "VLR-BS-028",
  },
  {
    name: "Ribbed Tank Top",
    category: "Basics",
    description: "A close-fit ribbed tank in a heavier cotton than most basics.",
    price: 799,
    images: ["https://images.unsplash.com/photo-1569025708622-8c9c95a090f1?w=900"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["White", "Black"],
    material: "95% cotton, 5% elastane",
    stock: 70,
    sku: "VLR-BS-029",
  },
  {
    name: "Relaxed Fit Polo",
    category: "Basics",
    description: "A relaxed pique polo with a longer body and dropped shoulder.",
    price: 1499,
    images: ["https://images.unsplash.com/photo-1575267685970-7fbabf6ed7b0?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Stone", "Navy"],
    material: "100% cotton pique",
    stock: 48,
    sku: "VLR-BS-030",
    isNewArrival: true,
  },
  {
    name: "Boxy Fit Hoodie",
    category: "Basics",
    description: "A heavyweight boxy hoodie with a dropped shoulder and raw hem.",
    price: 2199,
    images: ["https://images.unsplash.com/photo-1735860652246-8f777a1ffce3?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Grey"],
    material: "100% cotton fleece",
    stock: 42,
    sku: "VLR-BS-031",
  },
  {
    name: "Merino Base Layer",
    category: "Basics",
    description: "A fine-gauge merino tee built to wear alone or layered underneath.",
    price: 1999,
    images: ["https://images.unsplash.com/photo-1559555310-78c7c6121fc0?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Ivory"],
    material: "100% merino wool",
    stock: 37,
    sku: "VLR-BS-032",
  },
  {
    name: "Classic Fit Shirt",
    category: "Basics",
    description: "A no-fuss oxford shirt with a soft collar roll and classic fit.",
    price: 1699,
    images: ["https://images.unsplash.com/photo-1764084052707-f0d560ad67cf?w=900"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Light Blue"],
    material: "100% cotton oxford",
    stock: 44,
    sku: "VLR-BS-033",
  },

  // --- Denim (+7) ---
  {
    name: "Slim Fit Jean",
    category: "Denim",
    description: "A slim-through-the-leg jean in a mid-weight stretch denim.",
    price: 2699,
    images: ["https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=900"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Indigo", "Black"],
    material: "98% cotton, 2% elastane",
    stock: 50,
    sku: "VLR-DN-034",
  },
  {
    name: "Wide Leg Jean",
    category: "Denim",
    description: "A high-rise wide-leg jean in rigid denim with a long break.",
    price: 2899,
    images: ["https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=900"],
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Indigo", "Ecru"],
    material: "100% cotton denim",
    stock: 33,
    sku: "VLR-DN-035",
    isNewArrival: true,
  },
  {
    name: "Denim Trucker Jacket",
    category: "Denim",
    description: "A classic trucker jacket in rigid denim that fades with wear.",
    price: 3599,
    images: ["https://images.unsplash.com/photo-1527016021513-b09758b777bd?w=900"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Indigo", "Black"],
    material: "100% cotton denim",
    stock: 25,
    sku: "VLR-DN-036",
  },
  {
    name: "Distressed Skinny Jean",
    category: "Denim",
    description: "A skinny jean with light distressing at the knee and hem.",
    price: 2599,
    images: ["https://images.unsplash.com/photo-1640336437301-8368b53861ab?w=900"],
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Indigo"],
    material: "98% cotton, 2% elastane",
    stock: 38,
    sku: "VLR-DN-037",
  },
  {
    name: "Raw Selvedge Jean",
    category: "Denim",
    description: "An unwashed selvedge jean that molds to the wearer over time.",
    price: 3999,
    images: ["https://images.unsplash.com/photo-1614990354198-b06764dcb13c?w=900"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Raw Indigo"],
    material: "100% selvedge cotton denim",
    stock: 20,
    sku: "VLR-DN-038",
  },
  {
    name: "Denim Overall",
    category: "Denim",
    description: "A relaxed denim overall with adjustable straps and a chest pocket.",
    price: 3299,
    images: ["https://images.unsplash.com/photo-1675442141177-b99b70652416?w=900"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["Indigo"],
    material: "100% cotton denim",
    stock: 17,
    sku: "VLR-DN-039",
  },
  {
    name: "Cropped Straight Jean",
    category: "Denim",
    description: "A cropped straight-leg jean that sits cleanly at the ankle.",
    price: 2499,
    images: ["https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=900"],
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Indigo", "Black"],
    material: "100% cotton denim",
    stock: 41,
    sku: "VLR-DN-040",
  },
];

async function main() {
  console.log("Seeding VELARA database...");

  const admin = await prisma.user.upsert({
    where: { email: "admin@velara.com" },
    update: {},
    create: {
      name: "Velara Admin",
      email: "admin@velara.com",
      passwordHash: await bcrypt.hash("Admin123!", 12),
      role: "ADMIN",
    },
  });

  const customer = await prisma.user.upsert({
    where: { email: "customer@example.com" },
    update: {},
    create: {
      name: "Jordan Rivers",
      email: "customer@example.com",
      passwordHash: await bcrypt.hash("Customer123!", 12),
      role: "CUSTOMER",
    },
  });

  const categoryMap = new Map<string, string>();
  for (const c of categories) {
    const cat = await prisma.category.upsert({
      where: { name: c.name },
      update: {},
      create: { name: c.name, slug: slugify(c.name, { lower: true }), imageUrl: c.imageUrl },
    });
    categoryMap.set(c.name, cat.id);
  }

  for (const p of products) {
    const { category, ...rest } = p;
    await prisma.product.upsert({
      where: { sku: p.sku },
      update: { ...rest, categoryId: categoryMap.get(category)! },
      create: {
        ...rest,
        slug: slugify(p.name, { lower: true, strict: true }),
        categoryId: categoryMap.get(category)!,
      },
    });
  }

  console.log("Seed complete.");
  console.log(`Admin login: ${admin.email} / Admin123!`);
  console.log(`Customer login: ${customer.email} / Customer123!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
